name: Keep Streamlit App Awake
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering
jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl https://ccincpricing.streamlit.app/
